const { test, expect } = require('@playwright/test');
const fs = require('fs');
const path = require('path');

test.describe('ClimaSync NGO Authentication Flow', () => {
  const uniqueOrg = `TestNGO_${Date.now()}`;
  const uniqueEmail = `testngo_${Date.now()}@example.com`;
  const password = 'StrongPassword123!';

  test('should complete the full NGO registration, OTP verify, and dashboard flow', async ({ page }) => {
    page.on('console', msg => console.log('BROWSER CONSOLE:', msg.text()));
    page.on('pageerror', err => console.log('BROWSER ERROR:', err.message));
    test.setTimeout(90000); // 90s timeout to allow local python dev server to complete OTP email dispatch
    
    // 1. Visit the Registration Page
    await page.goto('/register');
    await expect(page.getByRole('heading', { name: 'Create Account' })).toBeVisible();

    // 2. Fill in Registration Form
    await page.getByLabel('Organization Name').fill(uniqueOrg);
    await page.getByLabel('Email Address').fill(uniqueEmail);
    // Note: Multiple fields have 'Password' in label, so using exact match
    await page.getByLabel('Password', { exact: true }).fill(password);
    await page.getByLabel('Confirm Password').fill(password);
    
    // Accept terms (ARIA label is "Accept terms")
    await page.getByRole('button', { name: 'Accept terms' }).click();

    // Submit Form
    await page.getByRole('button', { name: 'Create Account' }).click();

    // 3. OTP Verification Step
    // It should redirect to verification page automatically
    await expect(page).toHaveURL(/\/verify\?email=/, { timeout: 20000 });
    await expect(page.getByText('Verify Your Email')).toBeVisible();

    // Wait a couple of seconds for the backend to write the OTP file
    await page.waitForTimeout(2000); 

    // Read the locally exported OTP (generated by backend notification_service.py)
    const otpFilePath = path.join(__dirname, '..', '.latest_otp.txt');
    expect(fs.existsSync(otpFilePath)).toBeTruthy();
    
    const rawOtp = fs.readFileSync(otpFilePath, 'utf-8').trim();

    // Enter the OTP into the 6 separate digits inputs
    for (let i = 0; i < 6; i++) {
        await page.getByRole('textbox', { name: `Digit ${i + 1}` }).fill(rawOtp[i]);
    }

    // Submit OTP verification
    // The page is designed to auto-submit when the 6th digit is entered, so no manual click is required!

    // 4. Verify successful redirection to Dashboard
    await expect(page).toHaveURL('/dashboard', { timeout: 20000 });
    
    // Ensure the welcome banner or a dashboard element renders correctly
    await expect(page.getByText('Welcome back').first()).toBeVisible();
    await expect(page.getByText(uniqueOrg).first()).toBeVisible(); // Confirms user name displayed

    // 5. Test Side Navigation Features
    // Navigate to Tasks
    await page.getByRole('link', { name: /Tasks/i }).first().click();
    await expect(page).toHaveURL(/\/dashboard\/tasks/);
    await expect(page.getByRole('heading', { name: /Tasks/i }).first()).toBeVisible();

    // Navigate to Resources
    await page.getByRole('link', { name: /Resources/i }).first().click();
    await expect(page).toHaveURL(/\/dashboard\/resources/);
    await expect(page.getByRole('heading', { name: /Resources/i }).first()).toBeVisible();

    // Navigate to History
    await page.getByRole('link', { name: /History/i }).first().click();
    await expect(page).toHaveURL(/\/dashboard\/history/);
    await expect(page.getByRole('heading', { name: /History/i }).first()).toBeVisible();

    // Navigate to Notifications
    await page.getByRole('link', { name: /Notifications/i }).first().click();
    await expect(page).toHaveURL(/\/dashboard\/notifications/);
    await expect(page.getByRole('heading', { name: /Notifications/i }).first()).toBeVisible();

    // Navigate to Profile
    await page.getByRole('link', { name: /Profile|Settings/i }).first().click();
    await expect(page).toHaveURL(/\/dashboard\/profile/);
    await expect(page.getByText('Profile & Settings').first()).toBeVisible({ timeout: 15000 });

    // 6. Test Logout
    // Open user menu dropdown
    await page.locator('header').getByRole('button').last().click();
    // Click Logout
    await page.getByRole('button', { name: /Logout|Sign out/i }).first().click();
    
    // Verify redirection to Login or Home after logout
    await expect(page).toHaveURL(/\/login|\//);
  });
});
